# configs/tune_squared_hinge.yaml
name: "Squared Hinge Tuning Configuration"
loss: "squared_hinge"

globals:
  tune_epochs: 500
  loss_epsilon: 1.0e-4
  seed: 42
  patience: 3

objectives:
  - reg: "none"
    lam_grid: [0.0]
    optimizers:
      - name: "gd"
        lr_grid: [0.001, 0.01, 0.1] # learning rate bé hơn vì gradient của squared hinge có thể lớn
        backtracking:
          enabled: [False, True]
          armijo_alpha: [1e-4, 0.1, 0.5]
          armijo_beta: [0.5, 0.8]
      - name: "nag"
        lr_grid: [0.001, 0.01, 0.1]
        backtracking:
          enabled: [False, True]
          armijo_beta: [0.5, 0.8]
      - name: "newton"
        lr_grid: [1.0]
        backtracking:
          enabled: [False, True]
          armijo_alpha: [1e-4, 0.1, 0.5]
          armijo_beta: [0.5, 0.8]
      - name: "sgd"
        lr_grid: [0.001, 0.01, 0.1]
        schedule: ["fixed", "diminishing"]
        batch_size: [128, 256, 512]
        backtracking:
          enabled: [False]

  - reg: "l2"
    lam_grid: [1.0e-4, 1.0e-3, 1.0e-2]
    optimizers:
      - name: "gd"
        lr_grid: [0.001, 0.01, 0.1]
        backtracking:
          enabled: [False, True]
          armijo_alpha: [1e-4, 0.1, 0.5]
          armijo_beta: [0.5, 0.8]
      - name: "nag"
        lr_grid: [0.001, 0.01, 0.1]
        backtracking:
          enabled: [False, True]
          armijo_beta: [0.5, 0.8]
      - name: "newton"
        lr_grid: [1.0]
        backtracking:
          enabled: [False, True]
          armijo_alpha: [1e-4, 0.1, 0.5]
          armijo_beta: [0.5, 0.8]
      - name: "sgd"
        lr_grid: [0.001, 0.01, 0.1]
        schedule: ["fixed", "diminishing"]
        batch_size: [128, 256, 512]
        backtracking:
          enabled: [False]

  - reg: "l1"
    lam_grid: [1.0e-4, 1.0e-3, 1.0e-2]
    optimizers:
      - name: "gd"
        lr_grid: [0.001, 0.01, 0.1]
        backtracking:
          enabled: [False, True]
          armijo_beta: [0.5, 0.8]
      - name: "nag"
        lr_grid: [0.001, 0.01, 0.1]
        backtracking:
          enabled: [False, True]
          armijo_beta: [0.5, 0.8]
      - name: "sgd"
        lr_grid: [0.001, 0.01, 0.1]
        schedule: ["fixed", "diminishing"]
        batch_size: [128, 256, 512]
        backtracking:
          enabled: [False]
